version: '3.5'

services:
  angular:
    build: .
    command: start
    ports:
      - "4200:4200"
    volumes:
      - .:/app:delegated
    networks:
      selfconsult:
        aliases:
          - scontent-ui
    depends_on:
      - dummy-server

  dummy-server:
    build: .
    command: run-script dummy-server
    ports:
      - "3003:3003"
    networks:
      selfconsult:
        aliases:
          - scontent-server

networks:
  selfconsult:
    ipam:
      config:
        - subnet: 10.198.0.0/16
